import { Inter } from "next/font/google"
import "./globals.css"
import Sparkles from "@/components/Sparkles"
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " bg-gradient-to-b from-bgGradientFrom to-bgGradientTo min-h-screen text-indigo-50"
        }
      >
        <main className="p-4 w-full max-w-2xl mx-auto">
          <header className="flex justify-between my-2 sm:my-8">
            <Link href="/" className="flex gap-2">
              <Sparkles />
              <span>EpicCaptions</span>
            </Link>

            <nav className="flex gap-2 sm:gap-6 text-indigo-50/80">
              <Link href="/">Home</Link>
              <Link href="/pricing">Pricing</Link>
              <a href="mailto:contact@epiccaptions.com">Contact</a>
            </nav>
          </header>
          {children}
        </main>
      </body>
    </html>
  )
}
